// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGZddz1WVMXYJIOzAXo2k7G6Tlu3t7bi8',
    appId: '1:1092271704389:web:a84a88c2ad49c69c96d62c',
    messagingSenderId: '1092271704389',
    projectId: 'servico-facil-8ff18',
    authDomain: 'servico-facil-8ff18.firebaseapp.com',
    storageBucket: 'servico-facil-8ff18.firebasestorage.app',
    measurementId: 'G-56B0GWXT6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA11EbqsKx3NMhsz5MIPcC3T6_DhlGeI8w',
    appId: '1:1092271704389:android:4823f5439fc0633796d62c',
    messagingSenderId: '1092271704389',
    projectId: 'servico-facil-8ff18',
    storageBucket: 'servico-facil-8ff18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM_evqhUUEuOECKomngc2TPrRN3mo-nDk',
    appId: '1:1092271704389:ios:375043344e86f49696d62c',
    messagingSenderId: '1092271704389',
    projectId: 'servico-facil-8ff18',
    storageBucket: 'servico-facil-8ff18.firebasestorage.app',
    iosBundleId: 'com.example.servicoFacil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM_evqhUUEuOECKomngc2TPrRN3mo-nDk',
    appId: '1:1092271704389:ios:375043344e86f49696d62c',
    messagingSenderId: '1092271704389',
    projectId: 'servico-facil-8ff18',
    storageBucket: 'servico-facil-8ff18.firebasestorage.app',
    iosBundleId: 'com.example.servicoFacil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGZddz1WVMXYJIOzAXo2k7G6Tlu3t7bi8',
    appId: '1:1092271704389:web:083fcf0b1847eb4296d62c',
    messagingSenderId: '1092271704389',
    projectId: 'servico-facil-8ff18',
    authDomain: 'servico-facil-8ff18.firebaseapp.com',
    storageBucket: 'servico-facil-8ff18.firebasestorage.app',
    measurementId: 'G-3ZEEPV49V8',
  );
}
